dependencies:
  # - <organization/repo>@<version>
  - smartcontractkit/chainlink-brownie-contracts@1.1.1
  #- smartcontractkit/chainlink@2.0.0
  - OpenZeppelin/openzeppelin-contracts@3.4.0
compiler:
  solc:
    #version: 0.6.6
    remappings:
      #- '@chainlink=smartcontractkit/chainlink@2.0.0'
      #- '@chainlink=smartcontractkit/'
      # Neither of these is correct
      - '@chainlink=smartcontractkit/chainlink-brownie-contracts@1.1.1'
      #- '@chainlink=smartcontractkit/chainlink-brownie-contracts@0.2.1'
      - '@openzeppelin=OpenZeppelin/openzeppelin-contracts@3.4.0'
dotenv: .env
networks:
  #default: ganache-local
  default: development
  goerli:
    vrf_coordinator: '0x2Ca8E0C643bDe4C2E08ab1fA0da3401AdAD7734D'
    eth_usd_price_feed: '0xD4a33860578De61DBAbDc8BFdb98FD742fA7028e'
    link_token: '0x779877a7b0d9e8603169ddbd7836e478b4624789'
    verify: True
  mainnet-fork:
    eth_usd_price_feed: '0x5f4eC3Df9cbd43714FE2740f5E3616155c5b8419'
    verify: False
  development:
    keyhash: '0x79d3d8832d904592c0bf9818b621522c988bb8b0c05cdc3b15aea1b6e8db0c15'
    fee: 250000000000000000
    verify: False
  ganache-local:
    verify: False